spring:
 cloud:
   gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            allowedHeaders: '*'
            maxAge: 30  
            
      routes:
       - id: VendorService
         uri: lb://VENDORSERVICE
         predicates:
           - Path=/vendor/**
         filters:
           - AuthenticationFilter   
           
       - id: RestaurantService
         uri: lb://RESTAURANTSERVICE
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter  
           
       - id: CuisineService
         uri: lb://CUISINESERVICE
         predicates:
           - Path=/cuisine/**
         filters:
           - AuthenticationFilter  
 
       - id: OrderService
         uri: lb://ORDERSERVICE
         predicates:
           - Path=/order/**
         filters:
           - AuthenticationFilter

       - id: CustomerService
         uri: lb://CUSTOMERSERVICE
         predicates:
           - Path=/customers/**
         filters:
           - AuthenticationFilter
           
       - id: AuthService
         uri: lb://AUTHSERVICE
         predicates:
           - Path=/auth/**
         
         

 application:
  name: APIGateway
   
server:
  port: 8080   

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  main:
    web-application-type: reactive

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /customers/v3/api_docs
        name: Customer Service
      - url: /order/v3/api_docs
        name: Order Service
      - url: /auth/v3/api_docs
        name: Auth Service
      - url: /cuisine/v3/api_docs
        name: Cuisine Service
      - url: /restaurant/v3/api_docs
        name: Restaurant Service
      - url: /vendor/v3/api_docs
        name: Vendor Service
