

springdoc:
  swagger-ui:
    path: /auth/swagger-ui.html
  api-docs:
    path: /auth/v3/api_docs

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
